%% Example of classification using the Titanic dataset
% Data is imported as a table. Tables store data in column-orientd or
% tabular data. Table variables can have different data types and sizes as
% long as all varibles have the same number of rows. Table variables have 
% names, just as the fields of a structure have names. Use the summary function 
% to get information about a table

titanicData = readtable("titanic_data.csv");
% summary(titanicData)

%% Building the decision tree model
inputTable = titanicData;

% Change the Pclass from number to char (categorical variable) for
% convience 
inputTable.Pclass= num2str(inputTable.Pclass);

% Predictors and Response
% This code processes the data into the correct shape for training the
% model
predictorName = {'Pclass','Sex','Embarked'};
predictors = inputTable(:,predictorName);  % Could also be predictorNames = inputTable(:,[3,5,12]);
response = inputTable.Survived;

% Train the classifier
% This code specifies all the classifier options and trains the classifier
% option and trains the classifier
trainedDecisionTreeModel = fitctree(predictors,response);

% Graphic respresentation of the tree
view(trainedDecisionTreeModel,'mode','graph')
% text description (rule generated by the tree)
view(trainedDecisionTreeModel)

% Model preformance and evaluation on the training dataset
% Predicted class of the training 
predicatedY = resubPredict(trainedDecisionTreeModel); 

